current_project:
  - title: "ICT Creative Consilience Program"
    institution: "Ministry of Science and ICT"
    years: "July.2020 - Dec.2029"
  - title: "Development of 6H Next Generation Mobile Communications Technology"
    institution: "Ministry of Science and ICT"
    years: "April.2021 - Dec.2028"
  - title: "Free-space Active Propagation Channel Control Technology for Wireless Communications in mmWave and Beyond Frequencies"
    institution: "National Research Foundation Of Korea"
    years: "June.2022 - Feb.2025"
  - title: "Development of 2ms High-speed Touch Signal Processing Technology"
    institution: "Samsung display"
    years: "Mar.2023 - Feb.2025"
  - title: "Development a mmWave Radar-based Indoor Presence Detection Technology"
    institution: "Samsung Electronics"
    years: "Nov.2024 - Oct.2025"
past_project:
  - title: "Development a Platform for Machine Learning Model Validation for Intelligent Wireless Access Systems"
    institution: "ETRI"
    years: "July.2024 - Nov.2024"
  - title: "5G-Advanced Based Mobile Communication System 28 GHz Band RIS Creation"
    institution: "ETRI"
    years: "May.2024 - Nov.2024"
  - title: "Development a Platform for Intelligent Wireless Access Edgeserver Functional Validation"
    institution: "ETRI"
    years: "May.2024 - Nov.2024"
  - title: "Development of User Interface for Intelligent Wireless Access Edge Server Functional Verification"
    institution: "ETRI"
    years: "July.2023 - Nov.2023"
  - title: "Development of ultra-high performance/ultra-broadband network technology"
    institution: "ETRI"
    years: "April.2021 - Dec.2023"
  - title: "Building a Multi-Agent Frequency Sharing Simulator for Spectrum Challenge"
    institution: "ETRI"
    years: "April.2023 - Nov.2023"
  - title: "A Study on Terminal Networking Platform Technology"
    institution: "ETRI"
    years: "Sept.2013 - Jan.2014"
  - title: "A Study on the Adaptive and Distributed Access to Spectrum Holes in Cognitive Radio System"
    institution: "SeoulTech"
    years: "Dec.2010 - Nov.2011"
  - title: "A Study on the Application of Cognitive Radio Technologies to Femtocell Networks"
    institution: "National Research Foundation of Korea"
    years: "May.2011 - Apr.2014"
  - title: "Developing Multipath TCP Protocol for Throughput Enhancement and Network Resilience for LTE/Wi-Fi-Enabled Terminal"
    institution: "SK Telecom"
    years: "May.2013 – Nov.2013"
  - title: "Development of Digital Signage Platform Based on Bluetooth Low Energy"
    institution: "Small and Medium Business Administration"
    years: "May.2014 – Apr.2015"
  - title: "Development of Simulator for Core Network Quality Indication"
    institution: "SK Telecom"
    years: "July.2014 – Nov.2014"
  - title: "A Study on Small Cell Technologies for Effcient Utilization of Spectrum Resources"
    institution: "SeoulTech"
    years: "June.2014 – May 2015"
  - title: "A Study on the Aggregation of Multiple Asymmetric Wireless Links for Enhancing Throughput and QoS"
    institution: "National Research Foundation of Korea"
    years: "Sept.2014 – Feb.2017"
  - title: "Science-Technology-Culture Advanced Educational System (BK21)"
    institution: "National Research Foundation of Korea"
    years: "Sept.2013 – Feb.2015"
  - title: "Development of Road System for Autonomous Driving"
    institution: "Ministry of Land, Infrastructure and Transport"
    years: "June.2015 – May.2016"
  - title: "Study on Frequency Sharing Algorithm based on Radio Wave Circumstances"
    institution: "ETRI"
    years: "Apr.2020 – Nov.2020"
  - title: "Development of Baseband Ultra Density Network Hardware-in-the-Loop(HIL) Emulator"
    institution: "ETRI"
    years: "Mar.2020 - Nov.2020"
  - title: "Study on Frequency Sharing Algorithm based on Radio Wave Circumstances"
    institution: "ETRI"
    years: "Mar.2020 - Nov.2020"
  - title: "Wireless Energy Harvesting and Communications Research Center(ERC)"
    institution: "National Research Foundation of Korea"
    years: "Jun.2020 - Mar.2021"
  - title: "Development of GHz microwave energy charging system for smart IoT devices"
    institution: "KEPCO"
    years: "May.2018 - Apr.2021"
  - title: "Reconstruction of Non-Line-of-Sight Scene for VR/AR Contents"
    institution: "IITP"
    years: "Apr.2020 - Dec.2022"
  - title: "A study on mmWave Communications based on Reconfigurable Metasurface"
    institution: "National Research Foundation of Korea"
    years: "Mar.2020 - Feb.2023"
  - title: "Building a simulator for the Spectrum Challenge"
    institution: "ETRI"
    years: "May.2021 - Nov.2021"
  - title: "Advanced frequency sharing performance evaluation simulator for Spectrum Challenge"
    institution: "ETRI"
    years: "April.2022 - Nov.2022"
